// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHero: typeof import('./components/AppHero.vue')['default']
    IHeroiconsOutlineFilter: typeof import('~icons/heroicons-outline/filter')['default']
    IHeroiconsSolidChevronDown: typeof import('~icons/heroicons-solid/chevron-down')['default']
    IHeroiconsSolidSearch: typeof import('~icons/heroicons-solid/search')['default']
    IMdiCircleHalfFull: typeof import('~icons/mdi/circle-half-full')['default']
    IMdiCloseCircleOutline: typeof import('~icons/mdi/close-circle-outline')['default']
    IRiArrowRightLine: typeof import('~icons/ri/arrow-right-line')['default']
    IRiChatQuoteLine: typeof import('~icons/ri/chat-quote-line')['default']
    IRiCloseFill: typeof import('~icons/ri/close-fill')['default']
    IRiDoubleQuotesL: typeof import('~icons/ri/double-quotes-l')['default']
    IRiHeart2Fill: typeof import('~icons/ri/heart2-fill')['default']
    IRiHeart2Line: typeof import('~icons/ri/heart2-line')['default']
    IRiHeartFill: typeof import('~icons/ri/heart-fill')['default']
    IRiMoonClearLine: typeof import('~icons/ri/moon-clear-line')['default']
    IRiSaveLine: typeof import('~icons/ri/save-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    QuoteCard: typeof import('./components/QuoteCard.vue')['default']
    QuoteDialog: typeof import('./components/QuoteDialog.vue')['default']
    QuoteGallery: typeof import('./views/QuoteGallery.vue')['default']
    QuoteSearch: typeof import('./components/QuoteSearch.vue')['default']
    QuotesFilter: typeof import('./components/QuotesFilter.vue')['default']
  }
}

export { }
